### ISSUE TITLE
/category/****** Gives 404!

### ISSUE THREAD

**Issue by 66shayan** [desiredpersona/minimal-jekyll-theme#3]
Hey There,

First, thank you for the awesome theme! It's great. But no matter what I do, the theme can not build category/*** files! They are all pomp out 404 error.

I tried everything and everything seems right! Can you please help??

The /category/ and /tag/ pages are fine. But /category/life/ for example has 404 error etc.

**Comment by desiredpersona** [comment]
Sorry for delay.

I believe you are using the gem version of this theme. The issue is that the [jekyll-archives](https://github.com/jekyll/jekyll-archives) plugin is not supported/whitelisted as a [Github Pages](https://pages.github.com/versions/) dependency so thats why it isn't working.


Your options:
1. You may build the site locally and upload the contents of your `_site` folder to Github Pages.
2. Use [jekyll-remote-theme]( https://github.com/benbalter/jekyll-remote-theme) with Github Pages rather than the theme gem.
3. Host your website for free with [Netlify](https://www.netlify.com). (This is what I do)

**Comment by 66shayan** [comment]
Hey there,

I found the solution. I had to build the category folder and category pages one by one! That worked.
Basically everything needs to be built manually right now... pages, posts, categories, tags etc.
